name: Node.js Server route testing
run-name: ${{ github.actor }} is testing the server routes

on:
  push:
    branches:
      - test-branch
  pull_request:
    branches:
      - main

jobs:
  servertest:
    name: Install project and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
        env:
          CI: true