name: Node.js Server route testing
run-name: ${{ github.actor }} is testing the server routes

on:
  push:
    branches:
      - test-branch
  pull_request:
    branches:
      - main

jobs:
  servertest:
    name: Install project and run tests
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Wait for MongoDB to be ready
        run: |
          while ! nc -z localhost 27017; do
            echo "Waiting for MongoDB...";
            sleep 1;
          done

      - name: Run tests
        run: npm test
        env:
          CI: true
          MONGO_URL: mongodb://root:example@localhost:27017/testdb